<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="page-title well">
   <h1><?php echo Mage::helper('sales')->__('Returns') ?></h1>
</div>
<div class="block-content">
   <form id="oar_widget_orders_and_returns_form" action="<?php echo $this->getActionUrl() ?>" method="post" class="form-horizontal well" name="guest_post">
       <fieldset>
               <div class="control-group">
                   <label for="oar_order_id" class="control-label"><?php echo Mage::helper('sales')->__('Order ID') ?> <em>*</em></label>
	               <div class="controls">
	                   <input type="text" class="input-text required-entry span3" id="oar_order_id" name="oar_order_id" />
	               </div>
               </div>
               
                   <label><?php echo Mage::helper('sales')->__('Enter the billing last name and email/ZIP as in the order billing address') ?>.</label>
                
               <div class="control-group">
                   <label for="oar_billing_lastname" class="control-label"><?php echo Mage::helper('sales')->__('Billing Last Name') ?> <em>*</em></label>
	               <div class="controls">
	                   <input type="text" class="input-text required-entry span3" id="oar_billing_lastname" name="oar_billing_lastname" />
	               </div>
               </div>
               
               <div class="control-group">
                   <label class="control-label"><?php echo Mage::helper('sales')->__('Find Order By:') ?></label>
	               <div class="controls">
	                   <select name="oar_type" id="quick_search_type_id" class="select guest-select" title="" onchange="showIdentifyBlock(this.value);">
	                       <option value="email">Email Address</option>
	                       <option value="zip">ZIP Code</option>
	                   </select>
	               </div>
			   </div>
			   
               <div class="control-group" id="oar-email" style="clear:both;">
                   <label for="oar_email" class="control-label"><?php echo Mage::helper('sales')->__('Email Address') ?> <em>*</em></label>
	               <div class="controls">
	                   <input type="text" class="input-text validate-email required-entry span3" id="oar_email" name="oar_email" >
	               </div>
               </div>
               <div class="control-group" id="oar-zip" style="display:none;clear:both;">
                   <label for="oar_zip" class="control-label"><?php echo Mage::helper('sales')->__('Billing ZIP Code') ?> <em>*</em></label>
	               <div class="controls">
	                   <input type="text" class="input-text required-entry span3" id="oar_zip" name="oar_zip" />
	               </div>
			   </div>

           <div class="form-actions">
                   <button type="submit" title="Continue" class="btn"><span><span><?php echo Mage::helper('sales')->__('Continue') ?></span></span></button>
               </div>
       </fieldset>
   </form>
</div>
<script type="text/javascript">
//<![CDATA[
    if ($('quick_search_type_id').value == 'zip') {
        $('oar-zip').show();
        $('oar-email').hide();
    } else {
       $('oar-zip').hide();
       $('oar-email').show();
    }

   var dataForm = new VarienForm('oar_widget_orders_and_returns_form', true);

   function showIdentifyBlock(id)
   {
       if (id == 'zip') {
           $('oar-zip').show();
           $('oar-email').hide();
       } else if (id == 'email') {
           $('oar-zip').hide();
           $('oar-email').show();
       }
       return false;
   }
//]]>
</script>
