<?php $_items = $this->getReviewsCollection()->getItems();?>
<div class="box-collateral box-reviews" id="customer-reviews">
    <?php if (count($_items)):?>
    <div class="row-fluid">
        <div class="span12">

                <?php foreach ($_items as $_review):?>
                <div class="well">
                        <h6>
                            <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><?php echo $this->htmlEscape($_review->getTitle()) ?></a>
                        </h6>
                        <div class="row-fluid">
                            <div class="span6">
                                <blockquote>
                                    <p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?></p>
                                    <small> <?php echo $this->__('Review by <span>%s</span>', $this->htmlEscape($_review->getNickname())) ?> <cite><?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></cite></small>
                                </blockquote>
                            </div>
                            <?php $_votes = $_review->getRatingVotes(); ?>
                            <?php if (count($_votes)): ?>
                            <div class="span6">
                                <table class="ratings-table table">
                                    <col class="span1" />
                                    <col class="span2" />
                                    <tbody>
                                        <?php foreach ($_votes as $_vote): ?>
                                        <tr>
                                            <th><?php echo $this->escapeHtml($_vote->getRatingCode()) ?></th>
                                            <td>
                                                <div class="progress">
                                                    <div class="bar" style="width:<?php echo $_vote->getPercent() ?>%;"></div>
                                                </div>
                                            </td>
                                        </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                            <?php endif; ?>

                        </div>
                </div>
                <?php endforeach; ?>

                <?php echo $this->getChildHtml('toolbar') ?>

        </div>
    </div>
    <?php endif;?>
    <?php echo $this->getChildHtml('review_form') ?>
</div>
