<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="col2-set">
    <div class="box">
        <div class="box-title">
            <h3><?php echo $this->__('Address Book') ?></h3>
            <a href="<?php echo $this->getAddressBookUrl() ?>"><?php echo $this->__('Manage Addresses') ?></a>
        </div>
        <div class="row">
            <div class="span4 well">
                <h4><?php echo $this->__('Default Billing Address') ?></h4>
                <address>
                    <?php echo $this->getPrimaryBillingAddressHtml() ?><br />
                    <a href="<?php echo $this->getPrimaryBillingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>
            <div class="span4 well">
                <h4><?php echo $this->__('Default Shipping Address') ?></h4>
                <address>
                    <?php echo $this->getPrimaryShippingAddressHtml() ?><br />
                    <a href="<?php echo $this->getPrimaryShippingAddressEditUrl() ?>"><?php echo $this->__('Edit Address') ?></a>
                </address>
            </div>
        </div>
    </div>
</div>
