<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * @see Mage_Page_Block_Html_Notices
 */
?>
<?php if ($this->displayNoscriptNotice()): ?>
    <noscript>
        <div class="alert alert-custom">
        <a class="close" data-dismiss="alert">×</a>
            <p><?php echo $this->__('JavaScript seem to be disabled in your browser.'); ?>
            <?php echo $this->__('You must have JavaScript enabled in your browser to utilize the functionality of this website.'); ?></p>
        </div>
    </noscript>
<?php endif; ?>
<?php if ($this->displayDemoNotice()): ?>
    <div class="alert alert-custom fade in">
        <a class="close" data-dismiss="alert">×</a>
        <p class="demo-notice"><?php echo $this->__('This is a demo store. Any orders placed through this store will not be honored or fulfilled.') ?></p>
    </div>
<?php endif; ?>
