<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>

<?php $_product = $this->getProduct(); ?>
<?php $_options = Mage::helper('core')->decorateArray($this->getOptions()); ?>
<?php if ($_product->isSaleable()):?>
    <?php if (count($_options)): ?>
        <div>
        <?php foreach ($_options as $_option): ?>
            <?php if (!$_option->getSelections()): ?>
                <?php continue; ?>
            <?php endif; ?>
            <?php echo $this->getOptionHtml($_option) ?>
        <?php endforeach; ?>
        </div>
    <?php else: ?>
        <p><?php echo $this->__('No options of this product are available.') ?></p>
    <?php endif; ?>
<?php endif;?>
