<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Edit customer address template
 *
 * @see Mage_Customer_Block_Address_Edit
 */
?>
<?php if($this->getTitle()): ?>
<div class="page-title">
    <h1><?php echo $this->getTitle() ?></h1>
</div>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getSaveUrl() ?>" method="post" id="form-validate" class="form well">
<div class="row">
    <fieldset class="span4">
    <?php echo $this->getBlockHtml('formkey')?>
    <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
    <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
        <legend><h2 class="legend"><?php echo $this->__('Contact Information') ?></h2></legend>
            <div class="controls">
                <?php echo $this->getNameBlockHtml() ?>
            </div>
                <label class="control-label" for="company"><?php echo $this->__('Company') ?></label>
                <div class="controls">
                    <input type="text" name="company" id="company" title="<?php echo $this->__('Company') ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" class="input-text" />
                </div>
                <div class="control-group">
                    <label for="telephone" class="control-label"><em>*</em><?php echo $this->__('Telephone') ?></label>
                    <div class="controls">
                        <input type="text" name="telephone" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="telephone" />
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label" for="fax"><?php echo $this->__('Fax') ?></label>
                    <div class="controls">
                        <input type="text" name="fax" id="fax" title="<?php echo $this->__('Fax') ?>" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" class="input-text" />
                    </div>
                </div>
    </fieldset>
    <fieldset class="span4">
        <legend><h2 class="legend"><?php echo $this->__('Address') ?></h2></legend>
            <div class="control-group">
                <label for="street_1" class="control-label"><em>*</em><?php echo $this->__('Street Address') ?></label>
                <div class="controls">
                    <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" title="<?php echo $this->__('Street Address') ?>" id="street_1" class="input-text required-entry" />
                </div>
            </div>
        <?php for ($_i=2, $_n=$this->helper('customer/address')->getStreetLines(); $_i<=$_n; $_i++): ?>
                <div class="controls">
                    <input type="text" name="street[]" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet($_i)) ?>" title="<?php echo $this->__('Street Address %s', $_i) ?>" id="street_<?php echo $_i?>" class="input-text" />
                </div>
        <?php endfor ?>
                <div class="control-group">
                    <label for="city" class="control-label"><em>*</em><?php echo $this->__('City') ?></label>
                    <div class="controls">
                        <input type="text" name="city" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>"  title="<?php echo $this->__('City') ?>" class="input-text required-entry" id="city" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="region_id" class="control-label"><em>*</em><?php echo $this->__('State/Province') ?></label>
                    <div class="controls">
                        <select id="region_id" name="region_id" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                           <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                        </select>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                        //]]>
                        </script>
                        <input type="text" id="region" name="region" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" />
                    </div>
                </div>

                <div class="control-group">
                    <label for="zip" class="control-label"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="controls">
                        <input type="text" name="postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" title="<?php echo $this->__('Zip/Postal Code') ?>" id="zip" class="input-text validate-zip-international required-entry" />
                    </div>
                </div>
                <div class="control-group">
                    <label for="country" class="control-label"><em>*</em><?php echo $this->__('Country') ?></label>
                    <div class="controls">
                        <?php echo $this->getCountryHtmlSelect() ?>
                    </div>
                </div>
        
            <div<?php if($this->canSetAsDefaultBilling()) echo ' class="controls"' ?>>
                <?php if($this->isDefaultBilling()): ?>
                    <strong><?php echo $this->__('Default Billing Address') ?></strong>
                <?php elseif($this->canSetAsDefaultBilling()): ?>
                    <label for="primary_billing" class="checkbox">
                        <?php echo $this->__('Use as my default billing address') ?>
                        <input type="checkbox" id="primary_billing" name="default_billing" value="1" title="<?php echo $this->__('Use as My Default Billing Address') ?>" class="checkbox" />
                    </label>
                    
                <?php else: ?>
                    <input type="hidden" name="default_billing" value="1" />
                <?php endif; ?>
            </div>
            
            <div<?php if($this->canSetAsDefaultShipping()) echo ' class="controls"' ?>>
                <?php if($this->isDefaultShipping()): ?>
                    <strong><?php echo $this->__('Default Shipping Address') ?></strong>
                <?php elseif($this->canSetAsDefaultShipping()): ?>
                    <label for="primary_shipping" class="checkbox">
                        <?php echo $this->__('Use as my default shipping address') ?>
                        <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" title="<?php echo $this->__('Use as My Default Shipping Address') ?>" class="checkbox" />
                    </label>
                    
                <?php else: ?>
                    <input type="hidden" name="default_shipping" value="1" />
                <?php endif; ?>
            </div>
    </fieldset>
    </div>
    <div class="form-actions">
        <p class="help-block"><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo $this->__('Save Address') ?>" class="btn pull-right"><span><span><?php echo $this->__('Save Address') ?></span></span></button>
        <p class="back-link">
            <span class="icon-backward"></span>
            <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><?php echo $this->__('Back') ?></a>
        </p>

    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
//]]>
</script>
