<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 * @var $this Mage_Catalog_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<div class="alert fade in">
  <a class="close" data-dismiss="alert">×</a>
  <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php else: ?>
<div class="category-products">
    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
            <ul class="products-grid unstyled thubmnails row-fluid">
            <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?> span4">
                <div class="thumbnail">
                    <div class="caption">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                        <?php if($_product->isSaleable()): ?>
                            <?php /* Upcoming Event */ ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                            <p><?php echo $_product->getShortDescription() ?></p>
                            <button type="button" class="btn btn-primary" title="<?php echo $this->__('Register') ?>" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Register') ?></span></span></button>
                            <button type="button" class="btn" title="<?php echo $this->__('Details') ?>" onclick="setLocation('<?php echo $_product->getProductUrl() ?>')"><?php echo $this->__('Details') ?></button>
                        <?php else: ?>
                            <?php /* Passed Event */ ?>
                            <?php if($_product->getRatingSummary()): ?>
                                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            </ul>
        <?php endif ?>
        <?php endforeach ?>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>
</div>
