<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php if($this->getProductData()->getId()): ?>
<div class="product-review">
    <div class="page-title well">
        <h1><?php echo $this->__('Review Details') ?></h1>
    </div>
    <div class="row-fluid">
	    <div class="span12">
		    <div class="row-fluid">
		    
		        <div class="span4">
			        <a href="<?php echo $this->getProductData()->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getProductData()->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($this->getProductData(), 'small_image')->resize(300, 300); ?>" height="300" width="300" alt="<?php echo $this->htmlEscape($this->getProductData()->getName()) ?>" /></a>
			        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
			             <p class="label"><?php echo $this->__('Average Customer Rating') ?>:</p>
			             <?php echo $this->getReviewsSummaryHtml($this->getProductData()) ?>
			        <?php endif; ?>
			    </div>
    <div class="span8">
    <div class="product-details">
        <h2 class="product-name"><?php echo $this->htmlEscape($this->getProductData()->getName()) ?></h2>
        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
            <h3><?php echo $this->__('Product Rating:') ?></h3>
            <table class="ratings-table table">
            <?php foreach ($this->getRating() as $_rating): ?>
                <?php if($_rating->getPercent()): ?>
                    <tr>
                        <th><?php echo $this->__($this->escapeHtml($_rating->getRatingCode())) ?></th>
                        <td>
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
                            </div>
                        </td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
            </table>
        <?php endif; ?>
        
        <div>
            <blockquote>
                <p><?php echo nl2br($this->htmlEscape($this->getReviewData()->getDetail())) ?></p>
                <small><cite><?php echo $this->__('Product Review (submitted on %s):', $this->dateFormat($this->getReviewData()->getCreatedAt())) ?></cite></small>
            </blockquote>
            <p>

            </p>
            <p>

            </p>
        </div>
        
    </div>
    <div class="buttons-set">
        <p class="back-link">
            <small class="icon-backward"></small>
            <a href="<?php echo $this->getBackUrl() ?>"><?php echo $this->__('Back to Product Reviews') ?></a>
        </p>
    </div>
    
		    </div>
		    </div>
	    </div>
    </div>
    

    
</div>
<?php endif; ?>
