<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>

<?php $_product = Mage::registry('product'); ?>
<div class="buttons-set">
    <p class="back-link">
        <small class="icon-backward"></small>
        <a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('Back to Main Product Info') ?></a>
    </p>
</div>
