<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Last order sidebar
 *
 * @see Mage_Sale_Block_Reorder_Sidebar
 */
?>
<?php $_items = $this->getItems()?>
<?php if($_items): ?>
<div class="block block-reorder well">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Orders') ?></span></strong>
    </div>
    <form method="post" action="<?php echo $this->getFormActionUrl() ?>" id="reorder-validate-detail" class="form">
        <div class="block-content">
            <p class="block-subtitle"><?php echo $this->__('Last Ordered Items') ?></p>
            <?php $_showAddButtonFlag = false ?>
            <?php foreach ($_items as $_item): ?>
                <div class="controls">
                    <?php if ($this->isItemAvailableForReorder($_item)): ?>
                        <?php $_showAddButtonFlag = true ?>
                        <label class="checkbox">
                        <input type="checkbox" name="order_items[]" id="reorder-item-<?php echo $_item->getId() ?>" value="<?php echo $_item->getId() ?>" title="<?php echo $this->__('Add to Cart') ?>" class="checkbox validate-one-required-by-name" />
                            <a href="<?php echo $_item->getProduct()->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                        </label>
                        <script type="text/javascript">
                        //<![CDATA[
                            $('reorder-item-<?php echo $_item->getId() ?>').advaiceContainer = 'cart-sidebar-reorder-advice-container';
                        //]]>
                        </script>
                    <?php endif; ?>
<!--                    <p class="help-block">View products</p>-->
                </div>
            <?php endforeach; ?>
            <script type="text/javascript">decorateList('cart-sidebar-reorder')</script>
            <div id="cart-sidebar-reorder-advice-container"></div>
            <div class="actions">
                <?php if ($_showAddButtonFlag): ?>
                    <button type="submit" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-mini btn-success pull-right"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                <?php endif; ?>
                <a class="label" href="<?php echo $this->getUrl('customer/account') ?>"><?php echo $this->__('View All'); ?></a>
            </div>
        </div>
    </form>
</div>
<?php echo $this->getPagerHtml(); ?>
<script type="text/javascript">
//<![CDATA[
    var reorderFormDetail = new VarienForm('reorder-validate-detail');
//]]>
</script>
<?php endif ?>
