<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<script type="text/javascript">
//<![CDATA[
    var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
    var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var lastPrice;
//]]>
</script>
<form action="" id="co-payment-form" class="form">
    <fieldset>
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>
    <?php echo $this->getBlockHtml('formkey') ?>
    <p class="help-block"><?php echo $this->__('* Required Fields') ?></p>
    
</form>
        <div class="accordion" id="accordion2" style="display:none;">
            <div class="accordion-group">
                <div id="collapseOne" class="accordion-body collapse" style="height: 0px; ">
                    <div class="accordion-inner">
                        <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
                    </div>
                </div>
            </div>
        </div>        
<?php /*?><div class="tool-tip" id="payment-tool-tip" style="display:none;" rel="popover" data-content="And here's some amazing content. It's very engaging. right?" data-original-title="A Title" >
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div><?php */?>
<div class="form-actions" id="payment-buttons-container">
    <p class="back-link">
        <span class="icon-backward"></span>
        <a href="#" onclick="checkout.back(); return false;"><?php echo $this->__('Back') ?></a>
    </p>
    <button type="button" class="btn" onclick="payment.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
    <span class="please-wait" id="payment-please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Loading next step...') ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
    </span>
</div>
<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
       $('accordion2').toggle();
    }
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
