<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<?php
/**
 * Template for Mage_Customer_Block_Address_Book block
 * @var $test Mage_Customer_Block_Address_Book
 */
?>
<div class="page-title title-buttons well">
    <button type="button" title="<?php echo $this->__('Add New Address') ?>" class="btn pull-right" onclick="window.location='<?php echo $this->getAddAddressUrl() ?>';"><span><span><?php echo $this->__('Add New Address') ?></span></span></button>
    <h1><?php echo $this->__('Address Book') ?></h1>

</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="row">
        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultBilling()): ?>
            <div class="span3">
                <h3><?php echo $this->__('Default Billing Address') ?></h3>
                <address class="well">
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Billing Address') ?></a></p>
           </div>
        <?php else: ?>
            <div class="span3">
                <h3><?php echo $this->__('Default Billing Address') ?></h3>
                <?php echo $this->__('You have no default billing address in your address book.') ?>
            </div>
        <?php endif ?>

        <?php if($_pAddsses = Mage::getSingleton('customer/session')->getCustomer()->getDefaultShipping()): ?>
            <div class="span3">
                <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                <address class="well">
                    <?php echo $this->getAddressHtml(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>
                </address>
                <p><a href="<?php echo $this->getAddressEditUrl(Mage::getSingleton('customer/session')->getCustomer()->getAddressById($_pAddsses)) ?>"><?php echo $this->__('Change Shipping Address') ?></a></p>
            </div>
        <?php else: ?>
            <div class="span3">
                <h3><?php echo $this->__('Default Shipping Address') ?></h3>
                <p><?php echo $this->__('You have no default shipping address in your address book.') ?></p>
            </div>
        <?php endif ?>
    <div class="span3">
        <h3><?php echo $this->__('Additional Address Entries') ?></h3>
        <?php if($_pAddsses = $this->getAdditionalAddresses()): ?>
            <?php foreach($_pAddsses as $_address): ?>
                <address class="well">
                    <?php echo $this->getAddressHtml($_address) ?>
                </address>
                <p><a href="<?php echo $this->getUrl('customer/address/edit', array('id'=>$_address->getId())) ?>"><?php echo $this->__('Edit Address') ?></a> <span class="separator">|</span> <a href="#" class="link-remove" onclick="return deleteAddress('<?php echo $_address->getId() ?>');"><?php echo $this->__('Delete Address') ?></a></p>
            <?php endforeach; ?>
        <?php else: ?>
                <p><?php echo $this->__('You have no additional address entries in your address book.') ?></p>
        <?php endif ?>
    </div>
</div>
<div class="form-actions">
    <p class="back-link">
        <span class="icon-backward"></span>
        <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><?php echo $this->__('Back') ?></a>
    </p>
</div>
<script type="text/javascript">
//<![CDATA[
    function deleteAddress(addressId) {
        if(confirm('<?php echo $this->__('Are you sure you want to delete this address?') ?>')) {
            window.location='<?php echo $this->getDeleteUrl() ?>id/'+addressId;
        }
        return false;
    }
//]]>
</script>
