<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
<!--<div class="brand">-->
    <?php if ($this->getIsHomePage()): ?>
    <?php /*?>
        <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
     <?php */?>
    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="brand span3 active"><strong><?php echo $this->getLogoAlt() ?></strong></a>
    <?php else: ?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="brand span3"><strong><?php echo $this->getLogoAlt() ?></strong></a>
    <?php endif ?>
<!--</div>-->
<div class="nav-collapse">

        <?php echo $this->getChildHtml('topLinks') ?>
<?php /*?>
    <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
<?php */?>
                
    <?php echo $this->getChildHtml('topSearch') ?>
</div><!--/.nav-collapse -->

<?php //echo $this->getChildHtml('topContainer'); ?>
<?php //echo $this->getChildHtml('topMenu') ?>