<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</a>
    <?php if ($this->getIsHomePage()): ?>
    <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="brand span3 active"><strong><?php echo $this->getLogoAlt() ?></strong></a>
    <?php else: ?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="brand span3"><strong><?php echo $this->getLogoAlt() ?></strong></a>
    <?php endif ?>
<div class="nav-collapse"><?php echo $this->getChildHtml('topLinks') ?></div>
