<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="page-title well">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate" class="form-horizontal well">
    <fieldset>
        <legend><?php echo $this->__('Retrieve your password here') ?></legend>
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <div class="control-group">
                <label for="email_address" class="control-label"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="controls">
	                <div class="input-prepend">
	                	<span class="add-on">@</span>
	                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                    </div>

                </div>

        </div>
        <?php echo $this->getChildHtml('form.additional.info'); ?>
        <p class="help-block"><?php echo $this->__('* Required Fields') ?></p>
    <div class="form-actions">
	    <div class="span3">
	        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn btn-primary pull-right"><span><span><?php echo $this->__('Submit') ?></span></span></button>
	        <p class="back-link">
                <span class="icon-backward"></span>
                <a href="<?php echo $this->helper('customer')->getLoginUrl() ?>"><?php echo $this->__('Back to Login') ?></a>
            </p>
        </div>
    </div>
        </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
