<?php
/**
 * Shopping cart sidebar
 *
 * @see Mage_Checkout_Block_Cart_Sidebar
 * @var $this Mage_Checkout_Block_Cart_Sidebar
 */

?>
<?php if ($this->getIsNeedToDisplaySideBar()):?>
<?php $_cartQty = $this->getSummaryCount() ?>
<?php if ($_cartQty > 0): ?>
<div class="block block-cart well">
    <div class="block-title">
        <strong><span class="icon-shopping-cart"></span><span><?php echo $this->__('My Cart') ?></span></strong>
    </div>
    <div class="block-content">
        <div class="summary">
            <?php if ($_cartQty==1): ?>
                <p class="amount"><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?></p>
            <?php else: ?>
                <p class="amount"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
            <?php endif ?>

            <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
                <div class="actions">
                    <?php echo $this->getChildHtml('extra_actions') ?>
                    <button type="button" title="<?php echo $this->__('Checkout') ?>" class="btn btn-mini btn-danger" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>
<?php endif ?>
<?php endif;?>
