<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
        <div class="input-box">
            <input type="text" id="po_number" name="payment[po_number]" title="<?php echo $this->__('Purchase Order Number') ?>" class="input-text required-entry" value="<?php echo $this->htmlEscape($this->getInfoData('po_number')) ?>" placeholder="*<?php echo $this->__('Purchase Order Number') ?>"/>
        </div>
</div>
