<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div class="page-title well">
    <h1><?php echo $this->__('Newsletter Subscription') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('form_before')?>
<form action="<?php echo $this->getAction() ?>" method="post" id="form-validate" class="well form-inline">
    <fieldset>
        <?php echo $this->getBlockHtml('formkey')?>
        <legend><?php echo $this->__('Newsletter Subscription') ?></legend>
                <label for="subscription" class="checkbox">
                    <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php echo $this->__('General Subscription') ?>"<?php if($this->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
                    <?php echo $this->__('General Subscription') ?>
                </label>
            <div class="form-actions">
                <button type="submit" title="<?php echo $this->__('Save') ?>" class="btn btn-inverse pull-right"><span><span><?php echo $this->__('Save') ?></span></span></button>
                <p class="back-link">
                    <span class="icon-backward"></span>
                    <a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><?php echo $this->__('Back') ?></a>
                </p>
        
            </div>
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>