<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<button type="submit" title="<?php echo $this->__('Place Order') ?>" class="btn btn-large btn-danger btn-checkout pull-right" onclick="review.save();"><span><span><?php echo $this->__('Place Order') ?></span></span></button>
