<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<script type="text/javascript">
    $.noConflict();
    jQuery(document).ready(function($) {
        // Code that uses jQuery's $ can follow here.
        $('.nav-collapse').on('hidden', function () {
            $('.nav-collapse').show();
        })
    });
    // Code that uses other library's $ can follow here.
</script>