<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
<title><?php echo $this->pageTitle?></title>
<base href="<?php echo $this->getSkinUrl()?>" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="robots" content="*" />
<link rel="stylesheet" href="css/bootstrap.min.css" type="text/css" />
<style type="text/css">
    body {
        padding-top: 60px;
        padding-bottom: 40px;
    }
</style>
<link rel="stylesheet" href="css/bootstrap-responsive.css" type="text/css" />
<link rel="icon" href="images/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="<?php echo $this->getBaseUrl()?>" title="Magento Commerce" class="logo">Magento Commerce</a>
            </div>
        </div>
    </div>

    <div class="container">
        <!-- Main hero unit for a primary marketing message or call to action -->
        <div class="hero-unit">
            <?php require_once $contentTemplate; ?>
        </div>
    </div>

    <hr>

    <footer class="footer">
        <div class="container">
            <div class="pull-right">
                <img src="images/logo.gif" alt="Magento Commerce" />
            </div>
            <address class="copyright">Magento is a trademark of Magento Inc. Copyright &copy; 2012 Magento Inc.</address>
        </div>
    </footer>

<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>
