<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */

/**
 * @see Mage_Authorizenet_Block_Directpost_Form
 */
?>
<div id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
    <span class="label"><?php echo $this->__('You will be required to enter your payment details before you place an order.') ?></span>
</div>
