<?php
/**
 * Magento responsive theme
 *
 * @category    design
 * @package     bootstrapped_default
 * @copyright   Copyright (c) 2012 Magenthon (http://magenthon.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 * @author      Vedran Subotic <vedran@magenthon.com>
 */
?>
<div id="myCarousel" class="carousel slide"><!-- Carousel items -->
    <div class="carousel-inner">
        <div class="active item"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img01.jpg'); ?>" border="0" alt="" width="600" />
            <div class="carousel-caption">
                <p><a href="<?php echo $this->getUrl('sony-vaio-vgn-txn27n-b-11-1-notebook-pc.html'); ?>">Sony VAIO VGN-TXN27N/B 11.1" Notebook PC</a></p>
                <p>See all <a href="<?php echo $this->getUrl('electronics/computers/laptops.html'); ?>">Laptops</a></p>
            </div>
        </div>
        <div class="item"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img02.jpg'); ?>" border="0" alt="" width="600" />
            <div class="carousel-caption">
                <p><a href="<?php echo $this->getUrl('nine-west-women-s-lucero-pump.html'); ?>">Nine West Women's Lucero Pump</a></p>
                <p>See all <a href="<?php echo $this->getUrl('apparel/shoes.html'); ?>">Shoes</a></p>
            </div>
        </div>
        <div class="item"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img03.jpg'); ?>" border="0" alt="" width="600" />
            <div class="carousel-caption">
                <p><a href="<?php echo $this->getUrl('olympus-stylus-750-7-1mp-digital-camera.html'); ?>">Olympus Stylus 750 7.1MP Digital Camera</a></p>
                <p>See all <a href="<?php echo $this->getUrl('electronics/cameras/digital-cameras.html'); ?>">Digital Cameras</a></p>
            </div>
        </div>
        <div class="item"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img04.jpg'); ?>" border="0" alt="" width="600" />
            <div class="carousel-caption">
                <p><a href="<?php echo $this->getUrl('acer-ferrari-3200-notebook-computer-pc.html'); ?>">Acer Ferrari 3200 Notebook Computer PC</a></p>
                <p>See all <a href="<?php echo $this->getUrl('electronics/computers/laptops.html'); ?>">Laptops</a></p>
            </div>
        </div>
        <div class="item"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img05.jpg'); ?>" border="0" alt="" width="600" />
            <div class="carousel-caption">
                <p><a href="<?php echo $this->getUrl('asics-men-s-gel-kayano-xii.html'); ?>">ASICS&reg; Men's GEL-Kayano&reg; XII</a></p>
                <p>See all <a href="<?php echo $this->getUrl('apparel/shoes.html'); ?>">Shoes</a></p>
            </div>
        </div>
        <div class="item"><img class="product-img" src="<?php echo $this->getSkinUrl('images/media/best_selling_img06.jpg'); ?>" border="0" alt="" width="600" />
            <div class="carousel-caption">
                <p><a href="<?php echo $this->getUrl('coalesce-functioning-on-impatience-t-shirt.html'); ?>">Coalesce: Functioning On Impatience T-Shirt</a></p>
                <p>See all <a href="<?php echo $this->getUrl('apparel/shirts.html'); ?>">Shirts</a></p>
            </div>
        </div>
    </div>
    <!-- Carousel nav --> <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a></div>